#Performing EDA analysis on data provided to answer the following question 

#Who are the top bottom 10

##(a)Websites that have the largest count of news articles

In [23]:
%reload_ext autoreload
%autoreload 2

In [27]:
import pandas as pd
import os
#load the data 
data_dir = 'D:/Learning DSFS/news_correlation_10ac_week0/data'
news_data = pd.read_csv(os.path.join(data_dir, 'rating.csv'))
domains_data = pd.read_csv(os.path.join(data_dir,'domains_location.csv'))
traffic_data = pd.read_csv(os.path.join(data_dir,'traffic.csv'))
news_data

,article_id,source_id,source_name,author,title,description,url,url_to_image,published_at,content,category,article,title_sentiment
0,81664,NaN,Forbes,"Elizabeth Brownfield, Contributor, \n Elizabet...",superstar chef yannick alléno brings refined f...,Now open in Mayfair at Four Seasons Hotel Lond...,https://www.forbes.com/sites/elizabethbrownfie...,https://imageio.forbes.com/specials-images/ima...,2023-11-01 03:27:21.000000,"Pavyllon London, at Four Seasons Hotel London ...",Monaco,"pavyllon london, at four seasons hotel london ...",Neutral
1,81667,NaN,CNA,NaN,nice claim top spot in ligue 1 with late win a...,Nice moved into provisional first place in the...,https://www.channelnewsasia.com/sport/nice-cla...,https://onecms-res.cloudinary.com/image/upload...,2023-10-27 21:28:48.000000,Nice moved into provisional first place in the...,Monaco,nice moved into provisional first place in the...,Positive
2,81694,time,Time,Christina Larson / AP,amphibians are the world’s most vulnerable spe...,"The world’s frogs, salamanders, newts, and oth...",https://time.com/6320467/amphibians-most-vulne...,https://api.time.com/wp-content/uploads/2023/1...,2023-10-04 17:36:18.000000,"The worlds frogs, salamanders, newts and other...",Madagascar,"the world’s frogs, salamanders, newts and othe...",Negative
3,81695,NaN,Phys.Org,Sara Schmidt,image: rusty red waters in madagascar,Iron-rich sediment colors the red-orange water...,https://phys.org/news/2023-10-image-rusty-red-...,https://scx2.b-cdn.net/gfx/news/2023/image-rus...,2023-10-31 18:04:02.000000,Iron-rich sediment colors the red-orange water...,Madagascar,iron-rich sediment colors the red-orange water...,Neutral
4,81703,NaN,Digital Trends,Jason Struss,everything leaving max (formerly hbo max) in n...,From Gangs of London to Fear the Walking Dead ...,https://www.digitaltrends.com/movies/everythin...,https://www.digitaltrends.com/wp-content/uploa...,2023-10-23 23:09:18.000000,"Everything ends. No, I’m not having an existen...",Madagascar,"everything ends. no, i’m not having an existen...",Neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58351,781108,NaN,The Indian Express,PTI,"Have done no wrong, only did party work, says ...",The High Court today allowed Shivakumar to wit...,https://indianexpress.com/article/cities/banga...,https://images.indianexpress.com/2023/11/DK-Sh...,2023-11-29 10:57:22,Karnataka Deputy Chief Minister D K Shivakumar...,Home,Karnataka Deputy Chief Minister D K Shivakumar...,Neutral
58352,781129,NaN,Forbes,"Tom Sanderson, Senior Contributor, \n Tom Sand...",FC Barcelona Guarantees $77.6 Million Champion...,FC Barcelona have guaranteed at least $77.6 mi...,https://www.forbes.com/sites/tomsanderson/2023...,https://imageio.forbes.com/specials-images/ima...,2023-11-29 08:41:18,FC Barcelona have guaranteed at least $767.6 m...,Home,FC Barcelona have guaranteed at least $767.6 m...,Neutral
58353,781235,NaN,NPR,Brigid McCarthy,Three hospitals ignored her gravely ill fiancé...,"Forty years ago, Sarah Lubarsky came home from...",https://www.npr.org/2023/11/29/1215016001/heal...,https://media.npr.org/assets/img/2023/11/23/sa...,2023-11-29 10:01:12,The photo from David and Sarah Lubarsky's wedd...,Home,The photo from David and Sarah Lubarsky's wedd...,Negative
58354,781240,NaN,Forbes,"Gary Stern, Contributor, \n Gary Stern, Contri...",Kerber’s Farm: Bringing Farm To Table To Manha...,"A farmstand in Long Island, Kerber’s Farms has...",https://www.forbes.com/sites/garystern/2023/11...,https://imageio.forbes.com/specials-images/ima...,2023-11-29 13:44:33,Kerbers Farm: Bringing Farm To Table To Manhat...,Home,Kerber’s Farm: Bringing Farm To Table To Manha...,Neutral
58355,781308,NaN,Forbes,"Johan Hajji, Forbes Councils Member, \n Johan ...",Tips For Investing In Short-Term Rentals In Dubai,By exploring your options and keeping a few be...,https://www.forbes.com/sites/forbesbusinesscou...,https://imageio.forbes.com/specials-images/ima...,2023-11-29 14:00:00,Cofounder at UpperKey. Passionate about proper...,Home,Cofounder at UpperKey. Passionate about proper...,Neutral

In [39]:
def get_top_10_websites(news_data):
    top_10_websites = news_data.groupby('source_name')['article_id'].count().nlargest(10)
    print(top_10_websites)
    return top_10_websites

def get_bottom_10_websites(news_data):
    bottom_10_websites = news_data.groupby('source_name')['article_id'].count().nsmallest(10)
    
    
    return bottom_10_websites

get_top_10_websites(news_data)
get_bottom_10_websites(news_data)

source_name
ETF Daily News        16746
The Times of India     7504
GlobeNewswire          5423
Globalsecurity.org     3119
Forbes                 2784
BBC News               2113
ABC News               2058
Business Insider       2034
The Punch              1800
Al Jazeera English     1664
Name: article_id, dtype: int64

source_name
AllAfrica - Top Africa News     20
The Verge                      214
CNN                            267
Wired                          270
Euronews                       286
ReadWrite                      324
Gizmodo.com                    388
Android Central                522
Time                           600
CNA                            674
Name: article_id, dtype: int64

2 Websites with the hieghts number of visitors

In [42]:
def get_top_bottom_websites_traffic(traffic_data):
    bottom_10_websites = traffic_data.nlargest(10, 'GlobalRank')
    top_10_websites = traffic_data.nsmallest(10, 'GlobalRank')
    return top_10_websites, bottom_10_websites

top_websites, bottom_websites = get_top_bottom_websites_traffic(traffic_data)
print("Top 10 Websites with Highest Traffic:")
print(top_websites[['Domain', 'GlobalRank']])

print("\nBottom 10 Websites with Lowest Traffic:")
print(bottom_websites[['Domain', 'GlobalRank']])

Top 10 Websites with Highest Traffic:
                 Domain  GlobalRank
0            google.com           1
1          facebook.com           2
2           youtube.com           3
3           twitter.com           4
4         instagram.com           5
5          linkedin.com           6
6             apple.com           7
7         microsoft.com           8
8  googletagmanager.com           9
9         wikipedia.org          10

Bottom 10 Websites with Lowest Traffic:
                        Domain  GlobalRank
999999  toyotamusicfactory.com     1000000
999998          soderhomes.com      999999
999997           pinkwater.com      999998
999996             mt-lock.com      999997
999995              kireie.com      999996
999994         keith-baker.com      999995
999993          irishcycle.com      999994
999992                hmag.com      999993
999991    exploring-africa.com      999992
999990            eiretrip.com      999991

In [45]:
top_10_countries = traffic_data.groupby('Country')['Domain'].count().nlargest(10)
bottom_10_countries = traffic_data.groupby('Country')['Domain'].count().nsmallest(10)

print("Top 10 Countries with the Highest Number of News Media Organizations:")
print(top_10_countries)

print("\nBottom 10 Countries with the Lowest Number of News Media Organizations:")
top_10_countries = domains_data.groupby('Country')['SourceCommonName'].count().nlargest(10)
bottom_10_countries = domains_data.groupby('Country')['SourceCommonName'].count().nsmallest(10)

print("Top 10 Countries with the Highest Number of News Media Organizations:")
print(top_10_countries)

print("\nBottom 10 Countries with the Lowest Number of News Media Organizations:")
print(bottom_10_countries)

KeyError: 'Country'

In [46]:
top_10_tlds = domains_data['TLD'].value_counts().nlargest(10)
bottom_10_tlds = domains_data['TLD'].value_counts().nsmallest(10)

KeyError: 'TLD'